# automatically approve PRs submitted by Dependabot or Renofidev
# this will allow Dependabot to automatically merge dependency update PRs where CI passes
# from: https://github.com/hmarr/auto-approve-action
name: Auto approve dependency upgrades PRs

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'renofidev'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
